"""empty message

Revision ID: 9f9970dad1f2
Revises: 
Create Date: 2022-07-16 15:31:03.282954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9970dad1f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('alt_prices', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('is_coffee', sa.Boolean(), nullable=True),
    sa.Column('is_milk', sa.Boolean(), nullable=True),
    sa.Column('is_lact_free_milk', sa.Boolean(), nullable=True),
    sa.Column('is_vegan_milk', sa.Boolean(), nullable=True),
    sa.Column('is_tea', sa.Boolean(), nullable=True),
    sa.Column('is_matcha', sa.Boolean(), nullable=True),
    sa.Column('is_season', sa.Boolean(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('is_black_coffee', sa.Boolean(), nullable=True),
    sa.Column('is_fresh', sa.Boolean(), nullable=True),
    sa.Column('is_other', sa.Boolean(), nullable=True),
    sa.Column('is_deserts', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('max_to_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('product_type', sa.Text(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('users')
    op.drop_table('menu_item')
    # ### end Alembic commands ###
